<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/Android.props" />
    <PropertyGroup>
        <Version>1.1.2</Version>
        <Nullable>disable</Nullable>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <Import Project="$(ModRepositoryRoot)shared/ModEngineering/build/SharedDependencies.props" />
    <Target Name="CollectExtraPackageFiles" BeforeTargets="GetModPackageFiles">
        <ItemGroup>
            <ModPackageFile
                Include="$(ModRepositoryRoot)dependencies/font/ttcuyuanj"
                Destination="UserData/AbyssMod/ttcuyuanj"
            />
        </ItemGroup>
    </Target>
</Project>
